$activeBorderColor = rgba(ff9b88ee) rgba(ff7a64ee) 45deg
$inactiveBorderColor = rgba(4a3b42aa)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
